### ISSUE TITLE
odoo12安装成功后打开总账模块报错Error: QWeb2: Template 'accountcore.list2excel_t' not found

### ISSUE THREAD

**Issue by cwh643** [antdesigner/accountcore#137]
Uncaught Error: QWeb2: Template 'accountcore.list2excel_t' not found
http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:3374
追溯:
Error: QWeb2: Template 'accountcore.list2excel_t' not found
    at Object.exception (http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:3374:7)
    at Engine._render (http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:3419:103)
    at Engine.render (http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:3415:151)
    at Class.renderElement (http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:3672:1014)
    at http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:3682:6
    at http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:802:681
    at fire (http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:797:467)
    at Array.<anonymous> (http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:802:649)
    at Function.each (http://localhost:8269/web/content/1033-a3bd3b4/web.assets_common.js:625:767)

**Comment by cwh643** [comment]
可能是环境的问题，重新安装了一下没有报错
